name : Deploy Griffin Admin web to Ubuntu Server

on: 
  push: 
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Checkout
        
      - name: update package
        run: |
          flutter pub get
          dart run build_runner build -d

      - name: Build Flutter Web
        run: flutter build web

      - name:
          
